#!/usr/bin/python

import os
import time
print  ('            |-------------------------------------|')
print  ('            |solution by gaurav sanghvi 9930187981|')
print  ('            |-------------------------------------|')
print  ('                                       ')
print  ('                                       ')
print  ('                                       ')
print  ('                                       ')
print  ('                                       ')
print ('initializing to configure your wifi.....')
time.sleep(5)
os.system ('sudo modprobe -rv rtl8723be')
time.sleep(10)
print ('                ANALIZING WIFI MODE')
time.sleep(5)
os.system ('sudo modprobe -v rtl8723be ant_sel=0')
time.sleep(10)
print ('                TRYING TO GRAB SIGNAL')
time.sleep(5)
os.system ('sudo iw dev wlan0 scan | grep signal')
time.sleep(10)
print ('                ANALIZING WIFI MODE ')
time.sleep(5)
os.system ('sudo modprobe -rv rtl8723be')
time.sleep(10)
print ('                ANALIZING WIFI MODE')
time.sleep(5)
os.system ('sudo modprobe -v rtl8723be ant_sel=1')
time.sleep(10)
print ('                SETTING UP SIGNAL...ALMOST DONE')
time.sleep(5)
os.system ('sudo iw dev wlan0 scan | grep signal')
time.sleep(10)
print ('                DONE SETTING UP...ENJOY!!!!')

